# Generated by Django 5.0.1 on 2024-02-10 01:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_bd', models.CharField(max_length=7)),
                ('bd', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=7)),
                ('nombre_stock', models.CharField(max_length=255)),
                ('fecha_compra', models.DateTimeField()),
                ('num_acciones', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('moneda', models.CharField(max_length=4)),
                ('sector', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_bd', models.CharField(max_length=7)),
                ('bd', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=7)),
                ('nombre_stock', models.CharField(max_length=255)),
                ('fecha_inicio_seguimiento', models.DateTimeField()),
                ('precio_entrada_deseado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('moneda', models.CharField(max_length=4)),
                ('sector', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockcomprado',
            constraint=models.CheckConstraint(check=models.Q(('bd__in', ['dj30', 'ibex35'])), name='valores_bd'),
        ),
        migrations.AddConstraint(
            model_name='stockcomprado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_compra__lte', datetime.datetime(2024, 2, 11, 1, 16, 19, 804962, tzinfo=datetime.timezone.utc))), name='fecha_compra_no_futura'),
        ),
    ]
