# Generated by Django 5.0.1 on 2024-02-09 10:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockcomprado',
            name='fecha_compra_no_futura',
        ),
        migrations.AddConstraint(
            model_name='stockcomprado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_compra__lte', datetime.datetime(2024, 2, 10, 10, 31, 4, 484676, tzinfo=datetime.timezone.utc))), name='fecha_compra_no_futura'),
        ),
    ]
