# Generated by Django 4.2.7 on 2023-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.IntegerField()),
                ('Dividends', models.FloatField()),
                ('Stock_Splits', models.FloatField()),
                ('Ticker', models.CharField(max_length=10)),
                ('Previous_Close', models.FloatField()),
                ('Percent_Variance', models.FloatField()),
                ('MM20', models.FloatField()),
                ('MM50', models.FloatField()),
                ('MM200', models.FloatField()),
            ],
        ),
    ]
