name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analizar la app 'Analysis'
      run: |
        pylint --max-line-length=250 /FAT/Analysis

    - name: Analizar la app 'DashBoard'
      run: |
        pylint --max-line-length=250 /FAT/DashBoard

    - name: Analizar 'FAT'
      run: |
        pylint --max-line-length=250 /FAT/FAT     
    
    - name: Analizar la app 'News'
      run: |
        pylint --max-line-length=250 /FAT/News
    
    - name: Analizar la app 'Lab'
      run: |
        pylint --max-line-length=250 /FAT/Lab